data_presence_probability_range:
- 0.2
- 0.8
exploit_detection_probability_range:
- 0
- 0
firewall_rule_incoming_probability_range:
- 0
- 0
firewall_rule_outgoing_probability_range:
- 0
- 0
homogeneity_range:
- 0.1
- 0.1
knows_neighbor_probability_range:
- 0.1
- 0.3
max_services_per_category:
  ics: 1
  routers: 1
min_presence_each_category: 0.05
minimum_access_connectivity_threshold: 0.5
minimum_dos_connectivity_threshold: 0.5
minimum_knows_connectivity_threshold: 0.5
need_to_escalate_probability_range:
- 0.2
- 0.8
num_graphs: 1
num_nodes_range:
- 60
- 60
num_services_range:
- 1
- 2
partial_visibility_probability_range:
- 0.2
- 0.8
percentages:
- ics: 0.2474010668593478
  iot: 0.1747266683793814
  routers: 0.0682842435697577
  unix: 0.45487558574338305
  windows: 0.05471243544813008
probing_detection_probability_range:
- 0
- 0
service_shutdown_probability_range:
- 0
- 0
success_rate_probability_range:
- 0.6
- 1
value_range:
- 1
- 100
